### ISSUE TITLE
SPI only works with 4-8bit transfers

### ISSUE THREAD

**Issue by salkinium** [ARMmbed/mbed-hal-ksdk-mcu#31]
A transfer of a larger bit length (9 to 16bit) requires accessing 16bit words and while this can be configured, starting a 16 bit transfer doesn't set the `SPI_EVENT_INTERNAL_TRANSFER_COMPLETE` when required, probably due to still using 8bit lengths.

**Comment by 0xc0170** [comment]
Will patch tomorrow morning, thanks for reporting
