### ISSUE TITLE
mbed-hal asynch serial unittest fails

### ISSUE THREAD

**Issue by salkinium** [ARMmbed/mbed-hal-ksdk-mcu#34]
Running the serial asynch unit test on the k64f fails, with a [`SERIAL_EVENT_RX_OVERRUN_ERROR`](https://github.com/ARMmbed/mbed-hal-internal/blob/master/test/asynch-serial/main.cpp#L161).
The `serial_rx_interrupt()` is never called again, leading to a timeout of the test.

The exact output of the test is this:
```
{{timeout;20}}
{{host_test_name;default_auto}}
{{description;AsyncSerial}}
{{test_id;MBED_A1}}
{{start}}
New format: 8, 0, 1
=> ( 213)tx  213 IRQs
:161::FAIL: Expected XXXXXXXXXXXXXXXXXXXXXX0XXXXXXXXX Was XXXXXXXXXXXXXXXXXXXXXX1XXXXXXXXX
{{failure}}
{{end}}
```

I'm not sure if this is a bug in the KSDK or in the unittest.
However, the Unittest code is comparable to the [async serial example](https://github.com/ARMmbed/example-asynch-serial/blob/master/source/serial_asynch.cpp#L56-L57).

**Comment by 0xc0170** [comment]
Still relevant?

**Comment by salkinium** [comment]
No, all tests pass now.

**Comment by 0xc0170** [comment]
:disappointed_relieved:
