### ISSUE TITLE
UART Init sequencing error in HAL

### ISSUE THREAD

**Issue by len-samuelson** [ARMmbed/mbed-hal-ksdk-mcu#41]
The serial_init() code in serial_api.c fails to enable the Rx FIFO, as it enables the Transmitter before beginning the Rx init.

The obvious fix is to delay the transmitter enable until completing the Rx init. The original discovery of the problem and suggested fix is verified in a Freescale FRDM-K64F. The problem was only discovered with a UART speed setting of 7.5 mbit/sec, so it's not difficult to see why it was not caught earlier.

I can prepare this code in a pull request, though schedule constraints will prevent that from occurring for a few days.

```
    // Fifo Rx/Tx enabled by default. TX can be enabled/disable only if RE is disabled also
    if (tx != NC) {
        pin_mode(tx, PullUp);
        UART_HAL_SetTxFifoCmd(obj->serial.address, true);
        UART_HAL_FlushTxFifo(obj->serial.address);
        // Delay TX enable until completing RX settings
    }
    if (rx != NC) {
        pin_mode(rx, PullUp);
        UART_HAL_SetRxFifoCmd(obj->serial.address, true);
        UART_HAL_FlushRxFifo(obj->serial.address);
        UART_HAL_EnableReceiver(obj->serial.address);
    }
    if (tx != NC) {
        UART_HAL_EnableTransmitter(obj->serial.address);
    }
```

**Comment by 0xc0170** [comment]
Hi,

I recall there are some limitations to this for enabling fifo, stated in KSDK. A reference manual says for K64F: UARTx_PFIFO - This register must be written only when C2[RE] and C2[TE] are cleared/not set and when the data buffer/FIFO is empty. Which explains this issue.

Send PR please, and thanks for report

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-868

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1006
