### ISSUE TITLE
Race condition in HAL

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/mbed-hal-ksdk-mcu#8]
There is a race condition in our HAL.  The test for active state is dependent on buffer state, which leaves us open to a race condition during the interrupt handler.

I have examined SPI closely but I've found similar problems in the other transaction HAL peripherals.  

For SPI, if a higher priority interrupt fires at the wrong moment and tries to initiate a new SPI transaction during spi_irq_handler_asynch (any time after spi_api.c:370 and before SPI.cpp:143), it will override the callback which is already registered in the SPI object.

In addition to this, if a higher priority interrupt fires before a subsequent transaction is queued and this nested interrupt tries to start a new SPI transaction, then it can be lost when the item at the head of the queue is extracted.

To fix this, we need to add a busy flag at the mbed::SPI level.  The busy flag can be set immediately in SPI::transfer.  It needs to be set atomically, with all interrupts disabled.  I would anticipate something like this:
```C++
int SPI::transfer(uint16_t *tx_buffer, int tx_length, uint16_t *rx_buffer, int rx_length, void (*callback)(int), int event)
{
    bool queue;
    __disable_irq();
    queue = busy;
    busy = true;
    __enable_irq();
    if (queue || spi_active(&_spi)) {
        return queue_transfer(tx_buffer, tx_length, rx_buffer, rx_length, 8, callback, event);
    }
    start_transfer(callback, tx_buffer, tx_length, rx_buffer, rx_length, 8, event);
    return 0;
}
```
To match this code block, another change is needed in the irq handler.
```C++
void SPI::irq_handler_asynch(void)
{
    int event = spi_irq_handler_asynch(&_spi);
    if (_user_callback && (event & SPI_EVENT_ALL)) {
        _user_callback(event & SPI_EVENT_ALL);
    }

    if (event & SPI_EVENT_INTERNAL_TRANSFER_COMPLETE) {
        // SPI peripheral is free, dequeue transaction
        Transaction<SPI, spi_transaction_t> t;
        uint8_t index = spi_get_module(&_spi);
        // The following four lines are new.
        __disable_interrupts();
        bool dequeue = !_spi_module.empty();
        busy = dequeue;
        __enable_interrupts();
        if (dequeue) {
            _spi_module.pop(t, index);
            SPI* obj = t.get_object();
            spi_transaction_t* data = t.get_transaction();
            obj->start_transaction(data);
        }
    }
}
```

I expect that similar changes will be needed in I2C and UART.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-870

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1008

**Comment by 0xc0170** [comment]
I'll keep this open, as while fixing SPI in the drivers I found in i2c active a bug, and will check uart here in this module. I sent PR to mbed-drivers  to fix spi as stated above, thanks @bremoran for a fix proposal

**Comment by bremoran** [comment]
It might make sense to make a new issue to track UART and I2C, with specific details of the possible race conditions in each of those drivers.  That being the case, I believe we can close this issue once those two are opened.
